### ISSUE TITLE
Move from tslint to eslint

### ISSUE THREAD

**Issue by Sacro** [moleculerjs/moleculer-template-project-typescript#14]
TSLint is on security fixes only and will no longer be maintained a year from now. 

https://github.com/palantir/tslint/issues/4534

**Comment by faeron** [comment]
Should we move to https://github.com/typescript-eslint/typescript-eslint then, as many others do? @icebob

Maybe also possible to use just the eslint-config from moleculer core?

**Comment by icebob** [comment]
Ok, move to typescript-eslint.
