### ISSUE TITLE
moleculer init project-typescript transporter not configered

### ISSUE THREAD

**Issue by PaDreyer** [moleculerjs/moleculer-template-project-typescript#18]
Hello,

yesterday i've started using moleculer and i've tried to generate a typescript project with
`moleculer init project-typescript ts-moleculer-project`

**Info:**
macOS Catalina
Version 10.15.2

npm 6.9.0

These following things i chosed:
* API => yes
* communicate => yes
* transporter => tcp
* cache => yes
* cache solution => memory
* Dockerfiles => yes
* ESLint => yes
* Jest => yes

After that, **cd project**,** npm install** and **npm run dev**.

But i've got an error caused by **missing nats dependencies**.
**file**: moleculer.config.ts
in BrokerConfig Object property transporter is not set correctly i think.

After setting to TCP everything is fine

**Comment by RaphaelSchumacher** [comment]
Can confirm, had to install nats and spin off a nats container, same behavior as described by op.

Info:
windows 10 x64

npm: 6.14.5
moleculer: 0.13.13

**Comment by devalexandre** [comment]
this was already resolved in version 1.0.1 of the template, it is not in the cli @icebob

**Comment by devalexandre** [comment]
@PaDreyer this question. is it open yet?
