### ISSUE TITLE
Upgrade template to 0.14

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer-template-project-typescript#19]
@faeron could you upgrade this template to Moleculer v0.14?
It's not just dependencies upgrade, you should upgrade moleculer.config.js & meta.json, new products service, public folder...etc
Here is a list of changes from JS template: https://github.com/moleculerjs/moleculer-template-project/pull/19/files

**Comment by shawnmcknight** [comment]
@icebob I've started working on this one.

**Comment by icebob** [comment]
Thanks Shawn

**Comment by bahtiyarerden** [comment]
Hello @shawnmcknight  when will you resolve this issue?

**Comment by manchuwook** [comment]
Super excited to see the update to .14.

**Comment by RSchumacher13** [comment]
Super excited too :)

**Comment by RaphaelSchumacher** [comment]
Super excited too :)

**Comment by icebob** [comment]
Done.
