### ISSUE TITLE
Official template

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer-template-project-typescript#3]
Hi faeron,

can I add it to moleculer organization as typescript project template?

**Comment by faeron** [comment]
Yes totally!
If you don't miss anything I will transfer ownership to moleculer project.

**Comment by icebob** [comment]
Great! I think this template is done.

**Comment by faeron** [comment]
I just try to give you ownership/right to change ownership to moleculer organization.

**Comment by icebob** [comment]
Thx, I accepted the invite, but I have no right to see the "Settings" in the repo.

**Comment by faeron** [comment]
Seems to be a github restriction. Collaborators only have rights to push to repository. I PMed you on gitter.
