### ISSUE TITLE
Problems with metrics and tracking not working as config.

### ISSUE THREAD

**Issue by perjer4675** [moleculerjs/moleculer-template-project-typescript#52]
![unknown](https://user-images.githubusercontent.com/8032162/117086721-935d2280-ad77-11eb-8097-6bc49630286c.png)

**Comment by perjer4675** [comment]
First, I sent config in moleculer-runner --config dist/moleculer.config.js. 
Make it come to work

**Comment by icebob** [comment]
@AndreMaz could you check it plz?

**Comment by AndreMaz** [comment]
Hi @perjer4675 please take a look at https://github.com/moleculerjs/moleculer-template-project-typescript/pull/53. It has the fix for your problem

**Comment by perjer4675** [comment]
> Hi @perjer4675 please take a look at https://github.com/moleculerjs/moleculer-template-project-typescript/pull/53. It has the fix for your problem

Thank you very much. I think it's really cool for moleculer microservices.
